export const TRIGGER_LABELS: Record<string, string> = {
  manual: 'Manual',
  schedule: 'Scheduled',
  chat_command: 'Chat Command',
  webhook: 'Webhook',
  message: 'Message',
  email: 'Email',
  proposal_approved: 'Proposal Approved',
  proposal_rejected: 'Proposal Rejected',
  tool_error: 'Tool Error',
  workflow_completed: 'Workflow Completed',
  session_started: 'Session Started',
};

export const NODE_TYPE_LABELS: Record<string, string> = {
  tool_call: 'Tool Call',
  llm_decision: 'LLM Decision',
  send_message: 'Send Message',
  http_request: 'HTTP Request',
  condition: 'Condition',
  investigate: 'Investigate',
  inference: 'Inference',
};

export const HEALTH_CHECK_LABELS: Record<string, string> = {
  python_version: 'Python Version',
  dependencies_in_sync: 'Dependencies in Sync',
  config_file_loads: 'Config File Loads',
  config_schema: 'Config Schema',
  allowed_roots_cwd: 'Allowed Roots CWD',
  sqlite_dbs_readable: 'SQLite Databases Readable',
  llamacpp_reachable: 'llama.cpp Reachable',
  platform_prereqs: 'Platform Prerequisites',
  voice_prerequisites: 'Voice Prerequisites',
  trust_preset_resolves: 'Trust Preset Resolves',
  trust_preset_safe: 'Trust Preset Safe for Production',
  memory_epoch: 'Memory Epoch',
};

export const ROLE_LABELS: Record<string, string> = {
  admin: 'Administrator',
  trusted: 'Trusted User',
  user: 'User',
  child: 'Child',
};

export const TRUST_PRESET_LABELS: Record<string, string> = {
  paranoid: 'Paranoid',
  prompt_on_mobile: 'Prompt on Mobile',
  household: 'Household',
  developer: 'Developer',
};

export const CONFIG_KEY_LABELS: Record<string, string> = {
  trust_preset: 'Trust Preset',
  auto_approve_tools: 'Auto-approve Tools',
  prompt_on_mobile: 'Prompt on Mobile',
  model_path: 'Model Path',
  inference_url: 'Inference URL',
  context_window: 'Context Window',
  context_length: 'Context Length',
  max_tokens: 'Max Tokens',
  default_reasoning_budget: 'Default Reasoning Budget',
  bot_token: 'Bot Token',
  allowed_users: 'Allowed Users',
  allowed_rooms: 'Allowed Rooms',
  access_token: 'Access Token',
  scheduler_shell_exec: 'Scheduler Shell Exec',
  blocked_shell_patterns: 'Blocked Shell Patterns',
  subagent_write_local: 'Subagent Write Local',
  web_search_enabled: 'Web Search Enabled',
  voice_enabled: 'Voice Enabled',
  base_url: 'Base URL',
  model_name: 'Model Name',
  stream: 'Stream',
  homeserver: 'Homeserver',
  user_id: 'User ID',
  device_id: 'Device ID',
  rate_limit_edits_seconds: 'Rate Limit Edits (seconds)',
  sync_timeout_ms: 'Sync Timeout (ms)',
  database_url: 'Database URL',
  artifacts_dir: 'Artifacts Directory',
  allowed_roots: 'Allowed Roots',
  soul_path: 'Soul Path',
  compiled_cache_path: 'Compiled Cache Path',
  recompile_on_change: 'Recompile on Change',
  enabled: 'Enabled',
  host: 'Host',
  port: 'Port',
  auth_enabled: 'Auth Enabled',
  session_lifetime_hours: 'Session Lifetime (hours)',
  code_expiry_seconds: 'Code Expiry (seconds)',
  code_length: 'Code Length',
  imap_host: 'IMAP Host',
  imap_port: 'IMAP Port',
  smtp_host: 'SMTP Host',
  smtp_port: 'SMTP Port',
  username: 'Username',
  password: 'Password',
  password_env: 'Password Env Var',
  default_folder: 'Default Folder',
  drafts_folder: 'Drafts Folder',
  sent_folder: 'Sent Folder',
  max_fetch: 'Max Fetch',
  sanitize_html: 'Sanitize HTML',
  injection_scan: 'Injection Scan',
  injection_scanner_enabled: 'Injection Scanner Enabled',
  injection_entropy_threshold: 'Injection Entropy Threshold',
  injection_skip_filters_for_structured: 'Injection Skip Filters for Structured',
  egress_audit_enabled: 'Egress Audit Enabled',
  tick_interval_seconds: 'Tick Interval (seconds)',
  slot_dir: 'Slot Directory',
  pool_size: 'Pool Size',
  min_messages: 'Min Messages',
  max_chars: 'Max Characters',
  delegation_keywords: 'Delegation Keywords',
  research_keywords: 'Research Keywords',
  max_tool_calls_per_turn: 'Max Tool Calls per Turn',
  min_turns_to_activate: 'Min Turns to Activate',
  lookback_days: 'Lookback Days',
  cron: 'Cron',
  idle_minutes: 'Idle Minutes',
  lookback_turns: 'Lookback Turns',
  proposals_per_run: 'Proposals per Run',
  expire_days: 'Expire Days',
  model_override: 'Model Override',
  stt_model: 'STT Model',
  stt_device: 'STT Device',
  stt_compute_type: 'STT Compute Type',
  tts_engine: 'TTS Engine',
  tts_voice: 'TTS Voice',
  tts_speed: 'TTS Speed',
  model_cache_dir: 'Model Cache Directory',
  session_dir: 'Session Directory',
  headless: 'Headless',
  default_timeout_seconds: 'Default Timeout (seconds)',
  provider: 'Provider',
  api_key: 'API Key',
  max_results: 'Max Results',
  include_raw_content: 'Include Raw Content',
  search_depth: 'Search Depth',
  time_range: 'Time Range',
  requests_per_minute: 'Requests per Minute',
  burst_size: 'Burst Size',
  max_buckets: 'Max Buckets',
  system_prompt: 'System Prompt',
  max_iterations: 'Max Iterations',
  verbose: 'Verbose',
  use_curl_cffi_fallback: 'Use curl-cffi Fallback',
  trust_overrides: 'Trust Overrides',
  subagent_shell_exec: 'Subagent Shell Exec',
  subagent_email_send: 'Subagent Email Send',
  scheduler_email_send: 'Scheduler Email Send',
  self_management: 'Self Management',
  preset: 'Preset',
  http_version: 'HTTP Version',
  fallback_ips: 'Fallback IPs',
  connect_timeout_seconds: 'Connect Timeout (seconds)',
  read_timeout_seconds: 'Read Timeout (seconds)',
  long_poll_timeout_seconds: 'Long Poll Timeout (seconds)',
  voice_messages: 'Voice Messages',
};

export function label(map: Record<string, string>, key: string): string {
  return map[key] ?? key;
}
