export const TEXT = {
  common: {
    loading: 'Loading…',
    error: 'Something went wrong.',
    retry: 'Retry',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    confirm: 'Confirm',
    close: 'Close',
    back: 'Back',
    edit: 'Edit',
    create: 'Create',
    search: 'Search',
    filter: 'Filter',
    clear: 'Clear',
    none: 'None',
    unknown: 'Unknown',
    saving: 'Saving…',
    sending: 'Sending…',
    verifying: 'Verifying…',
    removing: 'Removing…',
    deleting: 'Deleting…',
    adding: 'Adding…',
    running: 'Running…',
    add: 'Add',
    remove: 'Remove',
    run: 'Run',
    skip: 'Skip',
  },
  login: {
    title: 'Hestia Dashboard',
    subtitle: 'Authenticate via your chat platform',
    step1Label: 'Select User',
    step2Label: 'Select Platform',
    step3Label: 'Enter Code',
    step1Description: 'Choose your user account to continue.',
    codePlaceholder: '000000',
    resend: 'Resend code',
    verify: 'Verify',
    noUsersTitle: 'No users available',
    noUsersDescription: 'No users configured. Contact your admin.',
    noPlatformsTitle: 'No platforms available',
    noPlatformsDescription: 'No platforms configured for this user.',
    selectedUserPrefix: 'Selected user: ',
    sendCodeVia: (platform: string) => `Send code via ${platform}`,
    backToUserSelection: '← Back to user selection',
    enterCodePrefix: 'Enter the code sent to ',
    expiresIn: (time: string) => `Expires in ${time}`,
    codeExpired: 'Code expired',
    backToPlatformSelection: '← Back to platform selection',
    codeExpiredPrefix: 'Code expired.',
    loadingTitle: 'Loading users…',
    loadingDescription: 'Please wait.',
  },
  profile: {
    title: 'User Profile',
    noUserTitle: 'No user found',
    noUserDescription: 'Please log in to view your profile.',
    displayNameLabel: 'Display Name',
    displayNamePlaceholder: 'Your name',
    roleLabel: 'Role',
    trustOverrideLabel: 'Personal trust override:',
    trustOverrideHelper: (global: string) =>
      `Overrides the global trust level (currently: ${global}).`,
    trustUsingGlobal: (global: string) =>
      `Using global trust level: ${global}. Select a preset to override.`,
    effectiveTrustLabel: 'Effective:',
    createdLabel: 'Created:',
    notesTitle: 'Notes',
    notesDescription: 'Facts about you that Hestia sees in every conversation.',
    notesPlaceholder: 'Facts about you that Hestia sees…',
    notesHelper: 'These notes are injected into Hestia\'s system prompt.',
    charactersSuffix: ' characters',
    saveNotes: 'Save Notes',
    saveError: (msg: string) => `Failed to save: ${msg}`,
    identitiesTitle: 'Identities',
    identitiesEmptyTitle: 'No identities linked',
    identitiesEmptyDescription:
      'Add an identity so Hestia knows how to reach you on other platforms.',
    verifiedBadge: '✓ verified',
    addIdentityButton: '+ Add identity',
    addIdentityTitle: 'Add Identity',
    addIdentityPlatformLabel: 'Platform',
    addIdentityUserLabel: 'User ID',
    addIdentityUserPlaceholder: 'e.g. @alice:example.com',
    roomsTitle: 'Rooms',
    roomsEmptyTitle: 'No rooms yet',
    roomsEmptyDescription:
      'Telegram and Matrix group chats are registered automatically when a message is received. Run `hestia migrate-users` to register existing groups.',
    editName: 'Edit name',
    removeIdentityConfirm: (platform: string, platformUser: string) =>
      `Remove identity ${platform}: ${platformUser}?`,
  },
  knowledge: {
    title: 'What Hestia Knows About You',
    memoriesTitle: 'Memories',
    memoriesDescription:
      'Session summaries and notes from your conversations with Hestia. You can delete any you disagree with.',
    memoriesEmptyTitle: 'No memories yet',
    memoriesEmptyDescription: 'Hestia learns about you during conversations.',
    memoriesDeleteConfirm: 'Delete this memory?',
    memoriesSoftDeleteConfirm: 'Move this memory to trash?',
    memoriesRestoreConfirm: 'Restore this memory?',
    memoriesSectionGlobal: 'Global',
    memoriesSectionTopic: (name: string) => `Topic: ${name}`,
    memoriesSectionTrash: 'Recently Deleted',
    memoriesTopicManageTitle: 'Topics',
    memoriesTopicManageDescription: 'Create and curate the scopes Hestia uses for retrieval.',
    memoriesCreateTopicPlaceholder: 'New topic name…',
    memoriesCreateTopicButton: 'Create',
    memoriesTopicEmptyTitle: 'No topics yet',
    memoriesTopicEmptyDescription: 'Create a topic to organize related memories.',
    memoriesTopicConversations: (count: number) =>
      `${count} conversation${count === 1 ? '' : 's'} subscribed`,
    memoriesTopicRename: 'Rename',
    memoriesTopicDelete: 'Delete',
    memoriesEditTitle: 'Edit Memory',
    memoriesContentLabel: 'Content',
    memoriesTagsLabel: 'Tags',
    memoriesScopeLabel: 'Scope',
    memoriesScopeGlobal: 'Global',
    memoriesScopeTopic: 'Topic',
    memoriesAddTopicLabel: 'Add topic',
    memoriesPin: 'Pin',
    memoriesUnpin: 'Unpin',
    memoriesDelete: 'Delete',
    memoriesRestore: 'Restore',
    memoriesSourceSession: (id: string) => `Source: ${id.slice(0, 8)}…`,
    memoriesCreated: (date: string) => `Created ${date}`,
    memoriesRecalled: (date: string) => `Recalled ${date}`,
    memoriesTrashEmptyTitle: 'No recently deleted memories',
    memoriesTrashEmptyDescription: 'Deleted memories remain restorable for a limited time.',
    styleTitle: 'Style Profile',
    styleDescription: 'How Hestia thinks you communicate.',
    styleEmptyTitle: 'No style metrics yet',
    styleEmptyDescription:
      'Style profiling is disabled or hasn\'t collected enough data.',
    sessionsTitle: 'Session History',
    sessionsEmptyTitle: 'No sessions yet',
    sessionsEmptyDescription: 'Your conversation history will appear here.',
    handoffsTitle: 'Handoff Summaries',
    handoffsDescription: 'What Hestia remembers from your last few sessions.',
    handoffsEmptyTitle: 'No handoff summaries yet',
    handoffsEmptyDescription:
      'These appear when Hestia carries context across sessions.',
    notesTitle: 'User Notes',
    notesDescription: 'Facts about you that Hestia sees in every conversation.',
    noNotesSaved: 'No notes saved.',
    editNotesLink: 'Edit notes on Profile →',
    tagFilterShowing: (count: number, total: number) =>
      `Showing ${count} of ${total} memories`,
    tagFilterClear: 'Clear filters',
  },
  scheduler: {
    title: 'Scheduled Tasks',
    createButton: '+ New Task',
    createTitle: 'New Task',
    editTitle: 'Edit Task',
    nameLabel: 'Name / Description',
    namePlaceholder: 'Daily summary',
    promptLabel: 'Prompt / URL',
    promptPlaceholder: 'https://example.com or prompt text',
    scheduleLabel: 'Schedule',
    enabledLabel: 'Enabled',
    runNow: 'Run now',
    runNowConfirmTitle: 'Run task now?',
    runNowConfirmDescription:
      'The task will be triggered on the next scheduler tick.',
    runNowConfirmRun: 'Run',
    deleteConfirmTitle: 'Delete task?',
    deleteConfirmDescription: 'This action cannot be undone.',
    emptyTitle: 'No scheduled tasks yet',
    emptyDescription:
      'Create one to run prompts or URLs on a recurring basis.',
    emptyAction: 'Create task',
    loadError: 'Failed to load tasks',
    tableTask: 'Task',
    tableSchedule: 'Schedule',
    tableNextRun: 'Next Run',
    tableStatus: 'Status',
    tableActions: 'Actions',
    statusEnabled: 'Enabled',
    statusDisabled: 'Disabled',
    statusError: 'Error',
  },
  adminUsers: {
    title: 'Users',
    accessDeniedTitle: 'Administrator access required',
    accessDeniedDescription:
      'You do not have permission to view this page.',
    createButton: '+ New User',
    createTitle: 'New User',
    editTitle: 'Edit User',
    deleteConfirm: (name: string) =>
      `Delete user "${name}"? This cannot be undone.`,
    deleteConfirmTitle: 'Delete user?',
    deleteConfirmDescription: 'This action cannot be undone.',
    addIdentityTitle: 'Add Identity',
    addIdentityPrompt:
      'User created. Would you like to add a platform identity now?',
    addIdentityPlatformLabel: 'Platform',
    addIdentityUserLabel: 'Platform User',
    skip: 'Skip',
    emptyTitle: 'No users yet',
    emptyDescription: 'Create a user to get started.',
    emptyAction: 'Create user',
    loadError: 'Failed to load users',
    displayNameLabel: 'Display Name',
    displayNamePlaceholder: 'Jane Doe',
    roleLabel: 'Role',
    trustPresetLabel: 'Trust Preset',
    notesLabel: 'Notes',
    notesPlaceholder: 'Optional notes about this user',
    tableName: 'Name',
    tableRole: 'Role',
    tableTrust: 'Trust',
    tableIdentities: 'Identities',
    tableRooms: 'Rooms',
    tableCreated: 'Created',
    tableActions: 'Actions',
  },
  errorDashboard: {
    title: 'Errors & Failures',
    emptyTitle: 'No errors found',
    emptyDescription: 'Hestia is running smoothly.',
    unresolvedLabel: 'Unresolved',
    filterAllTypes: 'All Types',
    filterAllStatuses: 'All Statuses',
    filterUnresolved: 'Unresolved',
    filterResolved: 'Resolved',
    filterIgnored: 'Ignored',
    typeWorkflow: 'Workflow',
    typeScheduler: 'Scheduler',
    typeSession: 'Session',
    debugModalTitle: 'Debug Prompt',
    debugModalDescription:
      'Copy this prompt and send it to Hestia to debug the error.',
    resolveButton: 'Resolve',
    ignoreButton: 'Ignore',
    debugButton: 'Debug',
    loadError: 'Failed to load errors',
    detailsButton: 'Details',
    hideButton: 'Hide',
    tableType: 'Type',
    tableSource: 'Source',
    tableMessage: 'Message',
    tableWhen: 'When',
    tableStatus: 'Status',
    tableActions: 'Actions',
    sourceIdFormat: (sourceId: string, type: string) =>
      `Source ID: ${sourceId} | Type: ${type}`,
  },
  healthChecks: {
    title: 'Health Checks',
    rerunButton: 'Re-run checks',
    rerunButtonLoading: 'Running…',
    lastChecked: (when: string) => `Last checked: ${when}`,
    passRate: (passRate: number, pass: number, total: number) =>
      `${passRate}% passing (${pass}/${total})`,
    noChecksAvailable: 'No checks available.',
    detailLabel: 'Detail:',
    remediationLabel: 'Remediation:',
  },
  workflowEditor: {
    sendMessageTitle: 'Send Message',
    sendMessageHelper:
      'Use {data.field_name} to reference trigger or upstream node outputs.',
    toolCallTitle: 'Tool Call',
    toolCallHelper: 'Arguments passed to the tool as a JSON object.',
    llmDecisionTitle: 'LLM Decision',
    llmDecisionBranchesHelper:
      'Possible outcomes. The LLM selects one based on the prompt.',
    conditionTitle: 'Condition',
    conditionHelper:
      'Supported: ==, !=, <, >, and, or, not. Reference data with data.field_name.',
    investigateTitle: 'Investigate',
    interactiveCheckbox: 'Wait for user response',
    interactiveTypeLabel: 'Response type',
    interactiveTypeButtons: 'Buttons',
    interactiveTypeText: 'Free text',
    interactiveTimeoutLabel: 'Timeout (seconds)',
    interactiveHelper:
      'If enabled, the workflow pauses until the user responds or the timeout expires.',
    propertiesTitle: 'Properties',
    deleteNode: 'Delete Node',
    idLabel: 'ID',
    typeLabel: 'Type',
    labelLabel: 'Label',
    toolNameLabel: 'Tool Name',
    toolNameHelper: 'The registered tool to invoke.',
    argsLabel: 'Args',
    argsHelper: 'JSON arguments passed to the tool.',
    argsJsonLabel: 'Args (JSON)',
    argsJsonPlaceholder: '{"query": "example"}',
    promptLabel: 'Prompt',
    charactersSuffix: ' characters',
    branchesLabel: 'Branches',
    addBranchPlaceholder: 'Add branch…',
    addBranchAriaLabel: 'Add branch',
    addButtonPlaceholder: 'Add button…',
    addButtonAriaLabel: 'Add button',
    platformLabel: 'Platform',
    platformHelper: 'Which adapter sends the message.',
    targetUserLabel: 'Target User',
    targetUserHelper: 'The user or room that receives the message.',
    conversationLabel: 'Target Conversation',
    conversationHelper: 'Choose a known conversation/session for this platform. Overrides Target User.',
    messageLabel: 'Message',
    previewLabel: 'Preview',
    characterCount: (count: number) => `${count} characters`,
    exceedsTelegramLimit: ' — Exceeds Telegram limit',
    mayExceedTelegramLimit: ' — May exceed Telegram limit',
    buttonLabelsLabel: 'Button labels',
    methodLabel: 'Method',
    urlLabel: 'URL',
    headersJsonLabel: 'Headers (JSON)',
    bodyLabel: 'Body',
    expressionLabel: 'Expression',
    conditionHelperAlt: 'A condition that evaluates to true or false.',
    topicLabel: 'Topic',
    depthLabel: 'Depth',
    toolsLabel: 'Tools',
    showSyntaxHelp: 'Show Syntax Help',
    hideSyntaxHelp: 'Hide Syntax Help',
    syntaxHelpVariables: 'Variables:',
    syntaxHelpVariablesValue: 'input.field_name',
    syntaxHelpComparisons: 'Comparisons:',
    syntaxHelpComparisonsValue: '==, !=, <, >, <=, >=',
    syntaxHelpLogic: 'Logic:',
    syntaxHelpLogicValue: 'and, or, not',
    syntaxHelpArithmetic: 'Arithmetic:',
    syntaxHelpArithmeticValue: '+, -, *, / (no power)',
    syntaxHelpLiterals: 'Literals:',
    syntaxHelpLiteralsValue: 'strings in quotes, numbers, True, False, None',
    syntaxHelpExamples: 'Examples:',
    syntaxHelpExamplesValue: 'input.status == "error", input.count > 10 and input.retry, not input.skipped',
    availableLabel: 'Available:',
    upstreamVariable: (nodeId: string) => `Node ${nodeId}: output`,
    insertVariablePlaceholder: 'Insert variable…',
    triggerVariable: (v: string) => `Trigger: ${v}`,
    headersObjectError:
      'Headers must be a JSON object, not an array or primitive.',
    invalidJsonError:
      'Invalid JSON — headers must be a JSON object like {"Authorization": "Bearer ..."}',
  },
  config: {
    trustPresetTitle: 'Trust Preset',
    invalid: 'Invalid',
    requiresRestart: 'Requires restart',
    resetToInitial: 'Reset to initial',
    generalSection: 'General',
    saveSuccess: 'Saved successfully',
    saveFailed: 'Save failed',
    hide: 'Hide',
    reveal: 'Reveal',
    readOnlyNotice: 'Configuration is read-only in the UI. Edit config.py directly and restart the server to apply changes.',
  },
  sessionDetail: {
    title: 'Session Detail',
    noSessionIdError: 'No session ID provided',
    backToKnowledge: '← Back to Knowledge',
    metadataTitle: 'Session Metadata',
    idLabel: 'ID',
    platformLabel: 'Platform',
    userLabel: 'User',
    startedLabel: 'Started',
    messagesLabel: 'Messages',
    transcriptTitle: 'Conversation Transcript',
    messagesTitle: 'Messages',
    messageRoleUser: 'User',
    messageRoleAssistant: 'Assistant',
    messageRoleSystem: 'System',
    emptyTitle: 'No turns yet',
    emptyDescription: 'This session has no conversation turns.',
    turnLabel: (id: string) => `Turn ${id.slice(0, 8)}…`,
  },
  dashboard: {
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    activeWorkflowsLabel: 'Active Workflows',
    scheduledTasksLabel: 'Scheduled Tasks',
    pendingProposalsLabel: 'Pending Proposals',
    recentSessionsLabel: 'Recent Executions',
    systemHealthLabel: 'System Health',
    healthUnknown: 'Unknown',
    healthPassing: (rate: number) => `${rate}% passing`,
    platformsLabel: 'Platforms',
    connected: 'Connected',
    disconnected: 'Disconnected',
    goToWorkflows: 'Go to Workflows',
    viewProfile: 'View Profile',
    runHealthCheck: 'Run Health Check',
    recentExecutionsTitle: 'Recent Executions',
    noExecutions: 'No executions yet.',
    tableWorkflow: 'Workflow',
    tableStatus: 'Status',
    tableTime: 'Time',
    tableElapsed: 'Elapsed',
    tableNodes: 'Nodes',
    loadError: 'Failed to load dashboard',
    noData: 'No data available.',
  },
  security: {
    title: 'Security & Health',
    auditFindingsTitle: 'Audit Findings',
    tabAll: 'All',
    tabWarnings: 'Warnings',
    tabInfo: 'Info',
  },
  styleProfile: {
    title: 'Style Profile',
    resetButton: 'Reset Profile',
    platformLabel: 'Platform',
    userLabel: 'User',
    identityLabel: 'Identity',
    emptyTitle: 'No style metrics yet',
    emptyDescription:
      'Hestia builds a style profile over time.',
    resetConfirmTitle: 'Reset style profile?',
    resetConfirmDescription: (
      count: number,
      platformUser: string,
      platform: string
    ) =>
      `This will delete all ${count} metrics for ${platformUser} on ${platform}.`,
    resetConfirmButton: 'Reset',
    resetError: 'Failed to reset profile',
  },
  proposals: {
    title: 'Proposals',
    tabPending: 'Pending',
    tabHistory: 'History',
    pendingEmptyTitle: 'No pending proposals yet',
    pendingEmptyDescription:
      'Hestia will create proposals when it needs confirmation for actions.',
    historyEmptyTitle: 'No history yet',
    historyEmptyDescription:
      'Approved or rejected proposals will appear here.',
    approveButton: 'Approve',
    rejectButton: 'Reject',
    acceptError: 'Failed to accept proposal',
    rejectError: 'Failed to reject proposal',
    created: (date: string) => `Created ${date}`,
  },
  workflows: {
    title: 'Workflows',
    createButton: 'New Workflow',
    defaultName: 'New Workflow',
    loading: 'Loading workflows…',
    empty: 'No workflows yet — create one to get started.',
    tableName: 'Name',
    tableTrigger: 'Trigger',
    tableLastRun: 'Last Run',
    tableActiveVersion: 'Active Version',
    tableActions: 'Actions',
    deleteConfirm: (name: string) => `Delete workflow "${name}"?`,
    createError: 'Failed to create workflow',
    deleteError: 'Failed to delete workflow',
  },
} as const;


