"""initial schema

Revision ID: 7368d8100cae
Revises: 
Create Date: 2026-04-10 13:46:59.508826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7368d8100cae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_user', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('slot_saved_path', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('temperature', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_platform_user', 'sessions', ['platform', 'platform_user', 'state'], unique=False)
    op.create_table('messages',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.Text(), nullable=True),
    sa.Column('tool_call_id', sa.String(), nullable=True),
    sa.Column('reasoning_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'idx')
    )
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cron_expression', sa.String(), nullable=True),
    sa.Column('fire_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduled_tasks_due', 'scheduled_tasks', ['next_run_at', 'enabled'], unique=False)
    op.create_index('idx_scheduled_tasks_session', 'scheduled_tasks', ['session_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_transition_at', sa.DateTime(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('reasoning_budget', sa.Integer(), nullable=False),
    sa.Column('status_msg_id', sa.String(), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_turns_session', 'turns', ['session_id', 'started_at'], unique=False)
    op.create_table('turn_transitions',
    sa.Column('turn_id', sa.String(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(), nullable=False),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.PrimaryKeyConstraint('turn_id', 'idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turn_transitions')
    op.drop_index('idx_turns_session', table_name='turns')
    op.drop_table('turns')
    op.drop_index('idx_scheduled_tasks_session', table_name='scheduled_tasks')
    op.drop_index('idx_scheduled_tasks_due', table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_table('messages')
    op.drop_index('idx_sessions_platform_user', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
