"""initial schema

Revision ID: ef029058c686
Revises:
Create Date: 2026-04-09 10:15:25.625790

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef029058c686"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("platform_user", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("last_active_at", sa.DateTime(), nullable=False),
        sa.Column("slot_id", sa.Integer(), nullable=True),
        sa.Column("slot_saved_path", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("temperature", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_sessions_platform_user",
        "sessions",
        ["platform", "platform_user", "state"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tool_calls", sa.Text(), nullable=True),
        sa.Column("tool_call_id", sa.String(), nullable=True),
        sa.Column("reasoning_content", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("session_id", "idx"),
    )
    op.create_table(
        "turns",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("last_transition_at", sa.DateTime(), nullable=False),
        sa.Column("iteration", sa.Integer(), nullable=False),
        sa.Column("reasoning_budget", sa.Integer(), nullable=False),
        sa.Column("status_msg_id", sa.String(), nullable=True),
        sa.Column("slot_id", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_turns_session", "turns", ["session_id", "started_at"], unique=False)
    op.create_table(
        "turn_transitions",
        sa.Column("turn_id", sa.String(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("from_state", sa.String(), nullable=False),
        sa.Column("to_state", sa.String(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["turns.id"],
        ),
        sa.PrimaryKeyConstraint("turn_id", "idx"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("turn_transitions")
    op.drop_index("idx_turns_session", table_name="turns")
    op.drop_table("turns")
    op.drop_table("messages")
    op.drop_index("idx_sessions_platform_user", table_name="sessions")
    op.drop_table("sessions")
    # ### end Alembic commands ###
